# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ludovic Bouguerra
author: Ludovic Bouguerra
email: bouguerra.ludovic@gmail.com
phone: +33 6 81 93 15 60

description: Entrepreneur et développeur freelance multimédia web / mobile / embarqué
picture: /images/profile.jpg
headline1: Développeur et formateur freelance 
headline2: "#Web #Mobile #Video #Embarqué #Streaming"
ga: 'UA-37459187-1'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.ludovicbouguerra.fr" # the base hostname & protocol for your site, e.g. http://example.com
technologies:
  - picture: images/home/technologies/aosp.png
    name: Android AOSP
  - picture: images/home/technologies/yocto.png
    name: Yocto
  - picture: images/home/technologies/buildroot.png
    name: Buildroot
  - picture: images/home/technologies/linux.png
    name: Linux, drivers
  - picture: images/home/technologies/gstreamer.png
    name: Gstreamer
  - picture: images/home/technologies/ffmpeg.png
    name: FFmpeg
  - picture: images/home/technologies/airplay.png
    name: Airplay
  - picture: images/home/technologies/chromecast.png
    name: Chromecast
  - picture: images/home/technologies/nginx.png
    name: Nginx
  - picture: images/home/technologies/wowza.png
    name: Wowza media server
  - picture: images/home/technologies/docker.png
    name: Docker
  - picture: images/home/technologies/aws.png
    name: AWS
  - picture: images/home/technologies/react.png
    name: React / React Native
  - picture: images/home/technologies/django.png
    name: Django
  - picture: images/home/technologies/celery.png
    name: Celery
  - picture: images/home/technologies/symfony.png
    name: Symfony
portfolio:
  - picture: images/home/portfolio/kalyzee.png
    name: Kalyzée
  - picture: images/home/portfolio/epitech.png
    name: Epitech
  - picture: images/home/portfolio/amu.png
    name: Aix Marseille Université
  - picture: images/home/portfolio/cnrs.png
    name: Laboratoire d'Astrophysique de Marseille
  - picture: images/home/portfolio/gep.png
    name: Groupe École pratique 
  - picture: images/home/portfolio/otonomy-aviation.png
    name: Otonomy aviation 
  - picture: images/home/portfolio/cs.png
    name: CS Group
  - picture: images/home/portfolio/colas.png
    name: Colas     
twitter_username: LBouguerra
github_username:  ludovic-bouguerra
linkedin: http://fr.linkedin.com/pub/ludovic-bouguerra/34/5a/214/
gplus_username: LudovicBouguerra
skype_username: ludovic.bouguerra
main_categories:
  - Architecture logicielle
  - Développement
  - Diffusion sur internet
  - FFmpeg
  - OpenERP
  - référencement
  - Systèmes d'informations
  - Vidéo
  - Virtualisation
plugins:
  - jekyll-paginate
paginate: 5
# Build settings
markdown: kramdown
gems:
  - jekyll-feed
sass:
    style: compressed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
    sass_dir: _sass
plugins:
  - jekyll-redirect-from
